### ISSUE TITLE
Replace feature images on homepage

### ISSUE THREAD

**Issue by earth2travis** [jonathanprozzi/raid-guild-cohort-docusaurus-v0#10]
- Replace the Docusaurus images with .svgs created by @ladylaurengrace

**Comment by jonathanprozzi** [comment]
I referenced this in the homepage content issue -- replacing these with @ladylaurengrace's illustrations would be great!

**Comment by jonathanprozzi** [comment]
This is done with dc8ebbf3a3332d70272ac2dc3880f8fb9b762f8c

Will be live next deploy. 

![homepage-icons](https://user-images.githubusercontent.com/9438776/119924397-7ca68780-bf41-11eb-82f0-bd91d26e5614.png)

I modified the HomepageFeatures component to take in our RaidIcons instead. We can swap these out for illustrations once they're ready.

Still thinking through some other content to add to this page but this is a start.
