### ISSUE TITLE
Move repo to Raid Guild account

### ISSUE THREAD

**Issue by earth2travis** [jonathanprozzi/raid-guild-cohort-docusaurus-v0#12]
Not a priority but we will probably want to move this repo from: jonathanprozzi to raid-guild on GitHub

**Comment by jonathanprozzi** [comment]
Yup, was thinking this for sure. Maybe once we demo to the group as part of our Season 1 'demo' we can roll into the RG GitHub.

**Comment by jonathanprozzi** [comment]
This is in progress -- talking with Saimano about transferring this over.

**Comment by jonathanprozzi** [comment]
Done! Saimano and I got this sorted out this morning. All of our issues, branches, and commit history moved over.

You'll want to update your remote origin url for push/pull. Happy to help if needed.
