### ISSUE TITLE
Gather Apprentices section content

### ISSUE THREAD

**Issue by earth2travis** [jonathanprozzi/raid-guild-cohort-docusaurus-v0#13]
[⚔️ Raid Guild Season 1](https://www.notion.so/1bdcb02f9d6c4ba69bd6629d5ea6dcea?v=5cd982e750da4dc8b290f35c08fc765c)

- Add column with checkbox to confirm they are okay being listed on the [Apprentices page](https://bafybeibqatfr3mo7amx7tlzasvyr6g2amxyiugj44xfagxj32c5ijxeerq.ipfs.infura-ipfs.io/apprentices)
- Add column for Primary Role that we can use to organize under headings on the [Apprentices page](https://bafybeibqatfr3mo7amx7tlzasvyr6g2amxyiugj44xfagxj32c5ijxeerq.ipfs.infura-ipfs.io/apprentices)
- Send out message to entire cohort to complete the new columns by a certain time that allows enough time for us to add the information to the page before Demo

**Comment by jonathanprozzi** [comment]
This is great. Once we have the list locked in I'll pull it into our mock apprentice data living in the utils folder. After the MVP we'll want to pull in this data via an API call but for the MVP we can use the mock. That may even be a way that people want to optionally do if they want a simpler way to pull it in without an API call to a database.

**Comment by earth2travis** [comment]
- Added the columns to Notion
- Sent messages out in the commons channel on Discord
- Gave a deadline for submissions of 5 PDT on May 27

**Comment by earth2travis** [comment]
Sent reminder message on in the commons channel

**Comment by jonathanprozzi** [comment]
I added all apprentices who responded and checked that they wanted to be included.

Since not everyone added their primaryRole I'm going to perhaps sort by name and then display primaryRole if they added it or maybe otherwise use the first role listed. I'll give that piece some thought.

**Comment by jonathanprozzi** [comment]
The  `<ApprenticeGrid />` now has a sorted prop that lets us sort alphabetically by name. apprentices will now be displayed alphabetically on the grid if thats true. For example:  `<ApprenticeGrid apprenticeData={apprenticeData} sorted />` sorts the incoming apprentice data by the name property and the grid is sorted by name. We can toggle this on/off, and extend to sort by other properties such as primary role in the future.

**Comment by jonathanprozzi** [comment]
Going to close this for now since we've come up with a way to sort the apprentices. We can always reopen if we want to think of additional sorting methods. I'm thinking we could specify the property or something so that this component is even more flexible.
