### ISSUE TITLE
Update site description meta tag

### ISSUE THREAD

**Issue by earth2travis** [jonathanprozzi/raid-guild-cohort-docusaurus-v0#17]

**Comment by earth2travis** [comment]
![image](https://user-images.githubusercontent.com/522182/119874360-20b11400-beeb-11eb-9150-77237030ffd5.png)

**Comment by jonathanprozzi** [comment]
This is fixed with 0043f4502064773e02b9fd4c28fc4e1d2c18251a 

I created a PageSeo component that wrapped react-helmet and was using that instead but there were conflicts. Instead, I ended up just using the title/description in the `<Layout />` component.

This will be live on the next deploy.

**Comment by jonathanprozzi** [comment]
![image](https://user-images.githubusercontent.com/9438776/119918665-e40b0a00-bf36-11eb-976c-3ae8f915b7bd.png)

Each page can have a different title and description. The `og:description` for social sharing is created by using the `description` prop in `<Layout/>`
