### ISSUE TITLE
Add Work to Internal Raid Tasks Sheet

### ISSUE THREAD

**Issue by earth2travis** [jonathanprozzi/raid-guild-cohort-docusaurus-v0#36]
Need to update the Finished tasks and projects tab:
https://docs.google.com/spreadsheets/d/1TyXmBesk_V_JImMv081zcEFi_A7f5nV1Q3kJEYveRRY/edit?pli=1#gid=350079227

**Comment by jonathanprozzi** [comment]
I added us -- we can add more detail/description. I submitted links for our repo and the most recent IPFS deploy.
