### ISSUE TITLE
Update homepage content

### ISSUE THREAD

**Issue by earth2travis** [jonathanprozzi/raid-guild-cohort-docusaurus-v0#4]
Write some words and replace images on the [homepage](https://bafybeibqatfr3mo7amx7tlzasvyr6g2amxyiugj44xfagxj32c5ijxeerq.ipfs.infura-ipfs.io/)

## Incomplete Thoughts

We have entered a new realm. Deep within the Ethereum ecosystem...DAO

This is our story, who we are and what we bring to Raid Guild

- Who we are
- What we bring
- Our story

**Comment by jonathanprozzi** [comment]
Working on this.  Made some changes with 8fbda284100348cfca98f5bcff584eef7e78d806

- Updated section titles, added a callout quote to the HomepageFeatures, and added some copy.

I think that this would be really enhanced with some of the illustrations being worked on!

![image](https://user-images.githubusercontent.com/9438776/119765210-ce3b0d80-be80-11eb-894c-9e0f5b408308.png)

**Comment by jonathanprozzi** [comment]
![image](https://user-images.githubusercontent.com/9438776/119923562-e2920f80-bf3f-11eb-9e12-363db0589327.png)

I modified the `HomepageFeatures` component to take in our RaidIcons instead. We can swap these out for illustrations once they're ready.

Still thinking through some other content to add to this page but this is a start.

**Comment by jonathanprozzi** [comment]
I started thinking about this a bit more. I think we could provide some layout components that allow for an alternating left/right/full width type of content display. We could possibly include links to Apprentices/Projects/Docs? in these sections.

I was starting to do this but I didn't want to without us all touching base first. After the v0 demo we can figure this out.

**Comment by earth2travis** [comment]
Made some updates last week and forgot to mention it here

**Comment by earth2travis** [comment]
These should roll live at our next deploy

**Comment by earth2travis** [comment]
Definitely more work to be done but think this is okay to move to done. We should consider making a request to the cohort to add some additional or feature some content
