### ISSUE TITLE
Create form to gather memes

### ISSUE THREAD

**Issue by earth2travis** [jonathanprozzi/raid-guild-cohort-docusaurus-v0#7]
- Create an Airtable form to collect meme content
- Decide what size they should be
- Figure out how we want to handle attribution (Twitter, GitHub, Discord) links to creator
- Send out form to get submissions to add to docs

**Comment by earth2travis** [comment]
Form created in Airtable: https://airtable.com/shroE9qLVzLtTE2lh

**Comment by earth2travis** [comment]
Message sent to the memes channel on Discord

**Comment by earth2travis** [comment]
Images pushed to `static > img > memes`

**Comment by jonathanprozzi** [comment]
These are now included in the memes docs page. 

I converted the memes page to mdx so that we could use the `useBaseUrl` hook to use relative paths for the images. I also ran the images through image-optim just so they're a bit smaller.

**Comment by jonathanprozzi** [comment]
We can probably close this for now. I think that once the site is up (and once we turn this into a cohort/dao template) we can make a form that is on the page itself so that folks can contribute more memes.
